BUILD_TEST_TASK_TEMPLATE: &BUILD_TEST_TASK_TEMPLATE
  arch_check_script:
    - uname -am
  install_script: bundle install
  runtime_script: bundle exec rake package
  package_script: bundle exec rb2exe pact-broker-app.rb --target=$TARGET
  test_script: ./pact-broker-app

macos_arm_task: 
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  ruby_version_script: ruby --version
  env:
    TARGET: oa64
  cirrus_cli_script: |
    chmod +x bin/*
  << : *BUILD_TEST_TASK_TEMPLATE
  binary_artifacts:
    path: "pkg/*"

macos_x64_task: 
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  ruby_version_script: ruby --version
  env:
    TARGET: ox64
    USE_ROSETTA: arch -x86_64
  cirrus_cli_script: |
    chmod +x bin/*
  rosetta_script: softwareupdate --install-rosetta --agree-to-license
  << : *BUILD_TEST_TASK_TEMPLATE
  binary_artifacts:
    path: "pkg/*"

linux_arm_task: 
  env:
    TARGET: la64
  arm_container:
    image: ruby:3.2.2-slim
    cpu: 1
    memory: 1G
  pre_req_script: apt update --yes && apt install --yes git zip curl
  cirrus_cli_script: |
    chmod +x bin/*
    mkdir -p /tmp/cirrus-ci/working-dir/bin
    touch /tmp/cirrus-ci/working-dir/bin/build
  bundler_setup_script: |
      gem install bundler -v 2.4.18
  << : *BUILD_TEST_TASK_TEMPLATE

linux_amd_task: 
  env:
    TARGET: lx64
  container:
    image: ruby:3.2.2-slim
    cpu: 1
    memory: 1G
  pre_req_script: apt update --yes && apt install --yes git zip curl
  ruby_setup_script: gem install bundler -v 2.4.18
  << : *BUILD_TEST_TASK_TEMPLATE
