BUILD_TEST_TASK_TEMPLATE: &BUILD_TEST_TASK_TEMPLATE
  arch_check_script:
    - uname -am
  install_script: bundle install
  runtime_script: bundle exec rake package
  package_script: bundle exec rb2exe pact-broker-app.rb --target=$TARGET
  test_script: ./pact-broker-app

macos_arm_task: 
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  ruby_version_script: ruby --version
  env:
    TARGET: ox64
  cirrus_cli_script: |
    chmod +x bin/*
  << : *BUILD_TEST_TASK_TEMPLATE
  binary_artifacts:
    path: "pkg/*"

# # BINARY_ env vars are set, so we only test our platform specific pact-ruby-standalone
# builder_linux_arm_task: 
#   env:
#     BINARY_OS: linux
#     BINARY_ARCH: arm64
#     PATH: "$HOME/.rbenv/bin:/root/.rbenv/shims:$PATH"
#   arm_container:
#     image: ruby:3.2.2-slim
#   pre_req_script:
#       apt update --yes && apt install --yes zip curl
#   << : *BUILD_TEST_TASK_TEMPLATE
#   binary_artifacts:
#     path: "pkg/*"