BUILD_TEST_TASK_TEMPLATE: &BUILD_TEST_TASK_TEMPLATE
  arch_check_script:
    - uname -am
  bundle_version_script: gem install bundler -v 2.4.18
  install_script: bundle install
  runtime_script: bundle exec rake package
  hello_world_script: echo "puts 'Hello world'" > test.rb
  package_script: bundle exec rb2exe test.rb --target=$TARGET
  test_script: ./test
  test_two_script: |
    mkdir test2
    cd test2
    echo "source 'https://rubygems.org'" > Gemfile
    echo "gem 'faker'" >> Gemfile
    echo "require 'faker'" > a.rb
    echo 'puts "Hello #{Faker::Name.name}"' >> a.rb
    cd ..
    bundle exec rb2exe test2/a.rb --add=test2 --target=$TARGET
    ./a
  test_three_script: |
    gem install rails
    rails new myproject
    bundle exec rb2exe --rails --add=myproject --target=$TARGET
    ./output

macos_arm_task: 
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  ruby_version_script: ruby --version
  env:
    TARGET: oa64
  cirrus_cli_script: |
    chmod +x bin/*
  << : *BUILD_TEST_TASK_TEMPLATE
  binary_artifacts:
    path: "pkg/*"

macos_x64_task: 
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  ruby_version_script: ruby --version
  env:
    TARGET: ox64
    USE_ROSETTA: arch -x86_64
  cirrus_cli_script: |
    chmod +x bin/*
  rosetta_script: softwareupdate --install-rosetta --agree-to-license
  << : *BUILD_TEST_TASK_TEMPLATE
  binary_artifacts:
    path: "pkg/*"

linux_arm_task: 
  env:
    TARGET: la64
  arm_container:
    image: ruby:3.2.2-slim
    cpu: 1
    memory: 1G
  pre_req_script: apt update --yes && apt install --yes git zip curl
  cirrus_cli_script: |
    chmod +x bin/*
    mkdir -p /tmp/cirrus-ci/working-dir/bin
    touch /tmp/cirrus-ci/working-dir/bin/build
  bundler_setup_script: |
      gem install bundler -v 2.4.18
  << : *BUILD_TEST_TASK_TEMPLATE

linux_amd_task: 
  env:
    TARGET: lx64
  container:
    image: ruby:3.2.2-slim
    cpu: 1
    memory: 1G
  pre_req_script: apt update --yes && apt install --yes git zip curl
  ruby_setup_script: gem install bundler -v 2.4.18
  << : *BUILD_TEST_TASK_TEMPLATE